name: 'Code Review using Local Ollama'
description: 'Perform a code review on code modified using Ollama'
inputs:
  llm-model:
    description: 'Name of the LLM model to use for code review'
    required: true
    default: 'codegemma:2b'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get modified files
      id: get-modified-files
      uses: tj-actions/changed-files@v43

    - name: Review modified files
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        for file in ${{ steps.get-modified-files.outputs.all_changed_files }}; do
          echo '{"model": "${{ inputs.llm-model }}", "prompt": "Review the following file:\n\n```\n$(cat $file)\n```", "stream": false}'
          modified_file_review=$(curl -s http://ollama:11434/api/generate -d '{"model": "${{ inputs.llm-model }}", "prompt": "Review the following file:\n\n```\n$(cat $file)\n```", "stream": false}' | jq -r '.response')
          file_comment="Ollama Code Review for \`$file\`:\n\n$modified_file_review"
          echo "$file_comment" >> ollama_review.txt
        done
   
        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ollama_review.txt)"
      shell: bash
