name: Dependency Check

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:


jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      # ##Fix to run action local with act https://stackoverflow.com/a/74666377/20281553
      # - name: Install curl (for nektos/act local CI testing)
      #   run: apt-get update && apt-get install build-essential curl pkg-config openssl -y
      # - name: Download Maven
      #   run: |
      #     curl -sL https://downloads.apache.org/maven/maven-4/4.0.0-rc-3/binaries/apache-maven-4.0.0-rc-3-bin.zip -o maven.zip
      #     apt-get update
      #     apt-get -y install unzip
      #     unzip -d /usr/share maven.zip
      #     rm maven.zip
      #     ln -s /usr/share/apache-maven-4.0.0-rc-3/bin/mvn /usr/bin/mvn
      #     echo "M2_HOME=/usr/share/apache-maven-4.0.0-rc-3" | tee -a /etc/environment
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'
      #     cache: maven
      # - name: Build with Maven
      #   run: mvn --batch-mode --update-snapshots verify
      - name: Depcheck
        # uses: dependency-check/Dependency-Check_Action@main
        # uses: diegri/Dependency-Check_Action@main
        uses: ./.github/actions/Dependency-Check_Action
        
        env:
          # actions/setup-java changes JAVA_HOME so it needs to be reset to match the depcheck image
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
            project: 'test'
            path: '.'
            format: 'HTML'
            out: 'reports' # this is the default, no need to specify unless you wish to override it
            more_args: >
                --failOnCVSS 7
                --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
            name: Depcheck report
            path: ${{github.workspace}}/reports